### ISSUE TITLE
Does not compile for Artemis boards.

### ISSUE THREAD

**Issue by mobreact** [sparkfun/SparkFun_Qwiic_Humidity_AHT20_Arduino_Library#2]
SparkFun_Qwiic_Humidity_AHT20/src/SparkFun_Qwiic_Humidity_AHT20.cpp:125:25: error: call of overloaded 'write(int)' is ambiguous
     _i2cPort->write(0x00);
In file included from /Users/trollin/Documents/Arduino/libraries/SparkFun_Qwiic_Humidity_AHT20/src/SparkFun_Qwiic_Humidity_AHT20.h:26,
                 from /Users/trollin/Documents/Arduino/libraries/SparkFun_Qwiic_Humidity_AHT20/src/SparkFun_Qwiic_Humidity_AHT20.cpp:26:
/Users/trollin/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/libraries/Wire/src/Wire.h:38:20: note: candidate: 'virtual size_t arduino::MbedI2C::write(uint8_t)'
     virtual size_t write(uint8_t data);
                    ^~~~~
In file included from /Users/trollin/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/core-api/api/Stream.h:25,
                 from /Users/trollin/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/core-api/api/Client.h:22,
                 from /Users/trollin/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/core-api/api/ArduinoAPI.h:29,
                 from /Users/trollin/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/Arduino.h:17,
                 from /Users/trollin/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/sdk/ArduinoSDK.h:9,
                 from <command-line>:
/Users/trollin/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/core-api/api/Print.h:50:12: note: candidate: 'size_t arduino::Print::write(const char*)'
     size_t write(const char *str) {
            ^~~~~
/Users/trollin/Documents/Arduino/libraries/SparkFun_Qwiic_Humidity_AHT20/src/SparkFun_Qwiic_Humidity_AHT20.cpp: In member function 'bool AHT20::triggerMeasurement()':
/Users/Documents/Arduino/libraries/SparkFun_Qwiic_Humidity_AHT20/src/SparkFun_Qwiic_Humidity_AHT20.cpp:136:25: error: call of overloaded 'write(int)' is ambiguous
     _i2cPort->write(0x00);
                         ^
In file included from /Users/Documents/Arduino/libraries/SparkFun_Qwiic_Humidity_AHT20/src/SparkFun_Qwiic_Humidity_AHT20.h:26,
                 from /Users/Documents/Arduino/libraries/SparkFun_Qwiic_Humidity_AHT20/src/SparkFun_Qwiic_Humidity_AHT20.cpp:26:
/Users/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/libraries/Wire/src/Wire.h:38:20: note: candidate: 'virtual size_t arduino::MbedI2C::write(uint8_t)'
     virtual size_t write(uint8_t data);
                    ^~~~~
In file included from /Users/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/core-api/api/Stream.h:25,
                 from /Users/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/core-api/api/Client.h:22,
                 from /Users/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/core-api/api/ArduinoAPI.h:29,
                 from /Users/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/Arduino.h:17,
                 from /Users/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/sdk/ArduinoSDK.h:9,
                 from <command-line>:
/Users/Library/Arduino15/packages/SparkFun/hardware/apollo3/2.0.6/cores/arduino/mbed-bridge/core-api/api/Print.h:50:12: note: candidate: 'size_t arduino::Print::write(const char*)'
     size_t write(const char *str) {
            ^~~~~
exit status 1
Error compiling for board RedBoard Artemis Nano.

**Comment by PaulZC** [comment]
Hi Ty (@mobreact ),

Apologies for the very slow reply!
I've corrected this issue in v1.0.1.

Best wishes,
Paul
